#############################################################################
# Makefile for building: libbitdht.a
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  libbitdht.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile libbitdht.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = g++
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -fPIC -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wall -DBE_DEBUG -g -fno-omit-frame-pointer -O2 -fPIC -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I.
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = temp/linux-g++-64/obj/

####### Files

SOURCES       = bitdht/bencode.c \
		bitdht/bdobj.cc \
		bitdht/bdmsgs.cc \
		bitdht/bdpeer.cc \
		bitdht/bdquery.cc \
		bitdht/bdhash.cc \
		bitdht/bdstore.cc \
		bitdht/bdnode.cc \
		bitdht/bdmanager.cc \
		bitdht/bdstddht.cc \
		bitdht/bdhistory.cc \
		util/bdnet.cc \
		util/bdthreads.cc \
		udp/udplayer.cc \
		udp/udpstack.cc \
		udp/udpbitdht.cc 
OBJECTS       = temp/linux-g++-64/obj/bencode.o \
		temp/linux-g++-64/obj/bdobj.o \
		temp/linux-g++-64/obj/bdmsgs.o \
		temp/linux-g++-64/obj/bdpeer.o \
		temp/linux-g++-64/obj/bdquery.o \
		temp/linux-g++-64/obj/bdhash.o \
		temp/linux-g++-64/obj/bdstore.o \
		temp/linux-g++-64/obj/bdnode.o \
		temp/linux-g++-64/obj/bdmanager.o \
		temp/linux-g++-64/obj/bdstddht.o \
		temp/linux-g++-64/obj/bdhistory.o \
		temp/linux-g++-64/obj/bdnet.o \
		temp/linux-g++-64/obj/bdthreads.o \
		temp/linux-g++-64/obj/udplayer.o \
		temp/linux-g++-64/obj/udpstack.o \
		temp/linux-g++-64/obj/udpbitdht.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		libbitdht.pro \
		libbitdht.pro
QMAKE_TARGET  = bitdht
DESTDIR       = lib/#avoid trailing-slash linebreak
TARGET        = libbitdht.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile lib/$(TARGET) 

staticlib: lib/$(TARGET)

lib/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d lib/ || mkdir -p lib/
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	-$(DEL_FILE) lib/$(TARGET)
	-$(MOVE) $(TARGET) lib/ 


Makefile: libbitdht.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		libbitdht.pro
	$(QMAKE) -o Makefile libbitdht.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
libbitdht.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile libbitdht.pro

qmake_all: FORCE

dist: 
	@test -d temp/linux-g++-64/obj/bitdht1.0.0 || mkdir -p temp/linux-g++-64/obj/bitdht1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/linux-g++-64/obj/bitdht1.0.0/ && (cd `dirname temp/linux-g++-64/obj/bitdht1.0.0` && $(TAR) bitdht1.0.0.tar bitdht1.0.0 && $(COMPRESS) bitdht1.0.0.tar) && $(MOVE) `dirname temp/linux-g++-64/obj/bitdht1.0.0`/bitdht1.0.0.tar.gz . && $(DEL_FILE) -r temp/linux-g++-64/obj/bitdht1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) lib/$(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

temp/linux-g++-64/obj/bencode.o: bitdht/bencode.c bitdht/bencode.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bencode.o bitdht/bencode.c

temp/linux-g++-64/obj/bdobj.o: bitdht/bdobj.cc bitdht/bdobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdobj.o bitdht/bdobj.cc

temp/linux-g++-64/obj/bdmsgs.o: bitdht/bdmsgs.cc bitdht/bencode.h \
		bitdht/bdmsgs.h \
		bitdht/bdobj.h \
		bitdht/bdpeer.h \
		bitdht/bdiface.h \
		util/bdnet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdmsgs.o bitdht/bdmsgs.cc

temp/linux-g++-64/obj/bdpeer.o: bitdht/bdpeer.cc bitdht/bdpeer.h \
		bitdht/bdiface.h \
		util/bdnet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdpeer.o bitdht/bdpeer.cc

temp/linux-g++-64/obj/bdquery.o: bitdht/bdquery.cc bitdht/bdquery.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdpeer.h \
		bitdht/bdobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdquery.o bitdht/bdquery.cc

temp/linux-g++-64/obj/bdhash.o: bitdht/bdhash.cc bitdht/bdhash.h \
		bitdht/bdpeer.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdstddht.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdhash.o bitdht/bdhash.cc

temp/linux-g++-64/obj/bdstore.o: bitdht/bdstore.cc bitdht/bdstore.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdpeer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdstore.o bitdht/bdstore.cc

temp/linux-g++-64/obj/bdnode.o: bitdht/bdnode.cc bitdht/bdnode.h \
		bitdht/bdpeer.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdquery.h \
		bitdht/bdobj.h \
		bitdht/bdstore.h \
		bitdht/bdhash.h \
		bitdht/bdhistory.h \
		bitdht/bencode.h \
		bitdht/bdmsgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdnode.o bitdht/bdnode.cc

temp/linux-g++-64/obj/bdmanager.o: bitdht/bdmanager.cc bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdstddht.h \
		bitdht/bdmanager.h \
		bitdht/bdnode.h \
		bitdht/bdpeer.h \
		bitdht/bdquery.h \
		bitdht/bdobj.h \
		bitdht/bdstore.h \
		bitdht/bdhash.h \
		bitdht/bdhistory.h \
		bitdht/bdmsgs.h \
		bitdht/bencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdmanager.o bitdht/bdmanager.cc

temp/linux-g++-64/obj/bdstddht.o: bitdht/bdstddht.cc bitdht/bdstddht.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdpeer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdstddht.o bitdht/bdstddht.cc

temp/linux-g++-64/obj/bdhistory.o: bitdht/bdhistory.cc bitdht/bdhistory.h \
		bitdht/bdpeer.h \
		bitdht/bdiface.h \
		util/bdnet.h \
		bitdht/bdobj.h \
		bitdht/bdstddht.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdhistory.o bitdht/bdhistory.cc

temp/linux-g++-64/obj/bdnet.o: util/bdnet.cc util/bdnet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdnet.o util/bdnet.cc

temp/linux-g++-64/obj/bdthreads.o: util/bdthreads.cc util/bdthreads.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/bdthreads.o util/bdthreads.cc

temp/linux-g++-64/obj/udplayer.o: udp/udplayer.cc udp/udplayer.h \
		util/bdthreads.h \
		util/bdnet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/udplayer.o udp/udplayer.cc

temp/linux-g++-64/obj/udpstack.o: udp/udpstack.cc udp/udpstack.h \
		util/bdthreads.h \
		util/bdnet.h \
		udp/udplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/udpstack.o udp/udpstack.cc

temp/linux-g++-64/obj/udpbitdht.o: udp/udpbitdht.cc udp/udpbitdht.h \
		udp/udpstack.h \
		util/bdthreads.h \
		util/bdnet.h \
		udp/udplayer.h \
		bitdht/bdiface.h \
		bitdht/bdmanager.h \
		bitdht/bdnode.h \
		bitdht/bdpeer.h \
		bitdht/bdquery.h \
		bitdht/bdobj.h \
		bitdht/bdstore.h \
		bitdht/bdhash.h \
		bitdht/bdhistory.h \
		bitdht/bdmsgs.h \
		bitdht/bencode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/linux-g++-64/obj/udpbitdht.o udp/udpbitdht.cc

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

